### PR TITLE
More up2date version included in nano

### PR DESCRIPTION
**Pull request by jlec**
Signed-off-by: Justin Lecher <jlec@gentoo.org>

### CODE REVIEW

**Comment by scopatz** [comment]
Feel free to replace the file, if you'd like. I don't think removing this one is needed.

**Comment by jlec** [comment]
You will get it for free when installing nano. So no need to duplicate that work.

**Comment by scopatz** [comment]
But only on gentoo, right?

**Comment by jlec** [comment]
No, it comes from nano directly

https://git.savannah.gnu.org/cgit/nano.git/tree/syntax/gentoo.nanorc

One of our devs is heavily involved in upstream development.

**Comment by scopatz** [comment]
So this is only available on the most recent version of nano?

**Comment by jlec** [comment]
I think 2.7.2 or so.

**Comment by gmcclins** [comment]
I don't think removing is good since there may be people still using an older version of nano for whatever reason. That said, and without ever really using that one. If upstream version is superior somehow, should we/can we include upstream's version?

Also since this PR wants to remove something that shouldn't get removed, can it be closed or denied?

**Pull request closed without merging**
