### PR TITLE
Added Batch and PowerShell support

### LINKED ISSUE #316: No syntax highlighting for Batch
This repository doesn't contain any syntax highlighting files for the Batch scripting language used on NT and DOS.

### PR DESCRIPTION
**Pull request by rashil2000**
Files forked from [mitchell486/nanorc](https://github.com/mitchell486/nanorc)

Fixes #316

### CODE REVIEW

**Comment by scopatz** [comment]
Thanks! That repo doesn't have a license. Can you please write these files so that they are not the same?

**Comment by rashil2000** [comment]
Sure, but sorry I don't understand what you mean by _writing_ them. What changes do I need to make?

**Comment by scopatz** [comment]
Well - we can't include these because @mitchell486 holds the right of first publish and has not provided a license for anyone to use them.  You'll need to create equivalent, but different, implementations that can be distributed with the license in this repo.  They have to be a completely separate implementation.

**Comment by DanteFalzone0** [comment]
Fixed by #323, close this request?

**Comment by scopatz** [comment]
Sure! I'll let @rashil2000 do so

**Comment by rashil2000** [comment]
Sure, give me a couple of days, I'll add support for PowerShell.

**Pull request closed without merging**
