### PR TITLE
Update HTML highlighting ruleset and merge Jinja2 templating rules into it

### PR DESCRIPTION
**Pull request by simon-v**
This brings the HTML syntax highlighting rules on par, if not ahead of the upstream version.

### CODE REVIEW

**Comment by scopatz** [comment]
Would you mind keeping the old j2 file around too just in case people are using it? Thanks!

**Comment by simon-v** [comment]
Not sure what for, as `html.j2.nanorc` is now provided by `html.nanorc`, and would trigger anyway if an `*.html.j2` file was opened; It shouldn't be necessary, unless people are heavily using `extendsyntax` to add to it (which, to be honest, sounds like a very awkward thing to do). But, if you really insist, perhaps, a symlink will do?

**Comment by scopatz** [comment]
A symlink would be fine

**Comment by simon-v** [comment]
Done.

**Comment by scopatz** [comment]
Thanks!

**Pull request merged**
