### PR TITLE
Add Rainbow CSV

### PR DESCRIPTION
**Pull request by simon-v**
Inspired by https://github.com/mechatroner/rainbow_csv

### CODE REVIEW

**Comment by scopatz** [comment]
Thanks!

**Comment by Rudxain** [comment]
Why isn't this `include`d?

**Comment by davidhcefx** [comment]
@Rudxain Please give this fork a try! It has all `*.nanorc` included 😃 
https://github.com/galenguyer/nano-syntax-highlighting

**Comment by Rudxain** [comment]
@davidhcefx Thanks for the suggestion! but I usually use [`hx`](https://helix-editor.com), so I don't need full-fledged config for `nano`

**Pull request merged**
