### PR TITLE
fix highlighting for v2.9.*

### PR DESCRIPTION
**Pull request by esler**
Get rid of message `Error in /usr/share/nano-syntax-highlighting/etc-hosts.nanorc on line 11: Color "normal" not understood.` after nano exits.

### CODE REVIEW

**Comment by scopatz** [comment]
If you would like to support older versions of nano, please copy the file to something named with an older version number, e.g. `etc-hosts.2.8.nanorc `

**Comment by esler** [comment]
My change is fully compatible with latest nano but it also works in older nano editor. Problem is that `nano` will throw an error when you open current highlighting. See

image

and 

image

**Comment by scopatz** [comment]
Yes I understand.  But normal is better than white.  New versions of nano shouldn't use white when they really mean the foreground color (normal).

**Comment by esler** [comment]
I thought that it would be ok do it since most of other files uses `white` too. I don't insist on this change... it would be ok to have support for <v3 nano :-)

**Comment by scopatz** [comment]
Yeah, most of the other files just haven't been updated.

**Comment by esler** [comment]
Perhaps you could create a branch where syntax highlighting for older nano (< v.3) will be and keep master up to date with latest nano editor.

**Comment by SuperSandro2000** [comment]
> Perhaps you could create a branch where syntax highlighting for older nano (< v.3) will be and keep master up to date with latest nano editor.

or you just update your nano to 4.X

**Comment by esler** [comment]
> or you just update your nano to 4.X
I'm not trying solve my problem rather that problem of people with older nano. Classic linux distros (RHEL, Debian) does not include latest nano. In fact most of them is using some prehistoric version 😞

**Comment by SuperSandro2000** [comment]
This solves your problem https://raw.githubusercontent.com/SuperSandro2000/dotfiles/master/programs/nano.sh

**Comment by scopatz** [comment]
Let me know when this is ready to go @esler!

**Comment by esler** [comment]
> Let me know when this is ready to go @esler!

It's ready to go 👍

**Comment by scopatz** [comment]
Thanks!

**Pull request merged**
