### PR TITLE
V2.9

### PR DESCRIPTION
**Pull request by mhf-ir**
Fix nano 2.9.3 compatibility:

https://github.com/scopatz/nanorc/issues/277

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
Closes #277

**Comment by mhf-ir** [comment]
@SuperSandro2000 when will be merged?

**Comment by SuperSandro2000** [comment]
I don't know. I can't merge stuff.

**Comment by scopatz** [comment]
Thanks, sorry about the delay!

**Pull request merged**
