### PR TITLE
Add kotlin

### PR DESCRIPTION
**Pull request by ritiek**
All thanks to [bjarneh](https://github.com/bjarneh) for making [kotlin.nanorc](https://github.com/bjarneh/kotkit/blob/master/misc/syntax/nano/kotlin.nanorc)

### CODE REVIEW

**Comment by scopatz** [comment]
Thanks for putting this in @Ritiek.

That repo does not have a license associated with it, so I cannot merge this in until @bjarneh give the OK.

**Comment by Ritiek** [comment]
I talked to @bjarneh [here](https://github.com/bjarneh/kotkit/issues/1) and he agreed.

**Comment by scopatz** [comment]
Hi @Ritiek, according to the license you still need to add the copyright line (`Copyright (c) 2014, bjarne holen`) to the file somewhere before this can be merged.

**Comment by Ritiek** [comment]
@scopatz Done :smile:

**Pull request merged**
