### PR TITLE
Fix syntax issues

### PR DESCRIPTION
**Pull request by SamuelEnglard**

### CODE REVIEW

**Comment by scopatz** [comment]
Thanks for the PR @SamuelEnglard. This seems mostly topical.  How does it fix the issue in #142? Please help me see

**Comment by SamuelEnglard** [comment]
These two things where what caused the issue. Bash would fail to parse the script therefore failing to run

**Comment by scopatz** [comment]
Oh I see, it is /bin/sh at the top, not /bin/bash.

**Comment by scopatz** [comment]
Thanks for the fix!

**Pull request merged**
